
// Generated by CoffeeScript 1.10.0
(function() {
	$('[name=case-check-01]').click(function() {
    if ($('input[name=case-check-01]:eq(1)').prop('checked')) {
       $(".case-01").css("display","none");
       $(".case-02").css("display","block");
    } else {
       $(".case-02").css("display","none");
       $(".case-01").css("display","block");
    }
});
  $(function() {}).foundation();

}).call(this);
